/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codechallenges05;

import linkedListDataStructure.LinkedList;

public class App {


    public static void main(String[] args) {
        LinkedList myLinkedList=new LinkedList();
        myLinkedList.insert(3);
        myLinkedList.insert(7);
        myLinkedList.insert(10);

        System.out.println("Linked List: " + myLinkedList);
        System.out.println("Includes 7? " + myLinkedList.includes(7));
        System.out.println("Includes 5? " + myLinkedList.includes(5));

    }
}
